# SonarCloud project configuration for oracle.oci
# Complete documentation: https://docs.sonarsource.com/sonarqube-cloud/

sonar.projectKey=ansible-collections_oracle.oci
sonar.organization=ansible-collections
sonar.projectName=oracle.oci

sonar.sources=.

sonar.tests=tests/unit,tests/integration
sonar.python.version=3.12
sonar.newCode.referenceBranch=main

sonar.exclusions=tests/**,.tox/**,.nox/**

# rules to ignore
sonar.issue.ignore.multicriteria=e1,e2
# dont require literals when creating empty lists, or dicts
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S7498
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.py

# dont require literals when creating empty sets
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S7496
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.py
