---
name: Sanity
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@4701d24e9110e9a4c8a15bc65f8e9d6e1c2d156e # main
    with:
      extra_matrix_entries: >-
        [{"name":"sanity-py3.11-2.16","python":"3.11"},
         {"name":"sanity-py3.12-2.16","python":"3.12"},
         {"name":"sanity-py3.11-2.18","python":"3.11"},
         {"name":"sanity-py3.12-2.18","python":"3.12"},
         {"name":"sanity-py3.13-2.18","python":"3.13"}]

  sanity-check:
    if: always()
    needs:
      - sanity
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
