---
name: Ansible lint
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@c81d405f1de6452c2ba7ddaca919afc65f8fe7ca # main

  ansible-lint-check:
    if: always()
    needs:
      - ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # release/v1
        with:
          jobs: ${{ toJSON(needs) }}
