---
name: Integration PR

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'plugins/**'
      - 'requirements.txt'
      - 'tests/integration/**'
      - 'Makefile'

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

jobs:
  determine-integration-targets:
    name: Determine integration targets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      run-integration: ${{ steps.determine.outputs.run-integration }}
      targets: ${{ steps.determine.outputs.targets }}
    steps:
      - name: Checkout base ref
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Determine integration targets
        id: determine
        uses: ./.github/actions/determine-integration-targets
        with:
          pr-number: ${{ github.event.pull_request.number }}

  integration-pr:
    name: Integration PR
    if: ${{ needs.determine-integration-targets.outputs.run-integration == 'true' }}
    needs:
      - determine-integration-targets
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: read
    environment:
      name: oci-integration
    env:
      OCI_TEST_COMPARTMENT_ID: ${{ secrets.OCI_TEST_COMPARTMENT_ID }}
      OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
      OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
      OCI_REGION: ${{ vars.OCI_REGION }}
      OCI_USER_FINGERPRINT: ${{ secrets.OCI_USER_FINGERPRINT }}
      OCI_USER_KEY_CONTENT: ${{ secrets.OCI_USER_KEY_CONTENT }}
      OCI_CONFIG_PROFILE: ${{ vars.OCI_CONFIG_PROFILE }}
    steps:
      - name: Checkout base ref
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Run OCI integration workflow
        uses: ./.github/actions/run-oci-integration
        with:
          ansible-ref: stable-2.18
          integration-targets: ${{ needs.determine-integration-targets.outputs.targets }}
          python-version: '3.12'

  integration-pr-check:
    if: always()
    needs:
      - determine-integration-targets
      - integration-pr
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # release/v1
        with:
          allowed-skips: integration-pr
          jobs: ${{ toJSON(needs) }}
